### `Problem 1`: Write a program that will give you in hand monthly salary after deduction on CTC - HRA(10%), DA(5%), PF(3%) and taxes deduction as below:

> Salary(Lakhs) : Tax(%)

*   Below 5 : 0%
*   5-10 : 10%
*   10-20 : 20%
*   aboove 20 : 30%

In [5]:
anual_ctc = int(input("Enter your ctc: "))
ctc_deduction = anual_ctc - anual_ctc*0.1 - anual_ctc*0.05 - anual_ctc*0.03
if ctc_deduction > 2000000 :
  total_deduction = ctc_deduction - 0.3*ctc_deduction
  monthly_salary = total_deduction/12
  print("monthly salary : ",monthly_salary)
elif  ctc_deduction > 1000000 and ctc_deduction <= 2000000 :
  total_deduction = ctc_deduction - 0.2*ctc_deduction
  monthly_salary = total_deduction/12
  print("monthly salary : ",monthly_salary)
elif ctc_deduction > 500000 and ctc_deduction <= 1000000 :
  total_deduction = ctc_deduction - 0.1*ctc_deduction
  monthly_salary = total_deduction/12
  print("monthly salary : ",monthly_salary)
else:
  monthly_salary = ctc_deduction/12
  print("monthly salary : ",monthly_salary)

Enter your ctc: 1200000
monthly salary :  73800.0

### `Problem 2`: Write a program that take a user input of three angles and will find out whether it can form a triangle or not.

In [ ]:
x = int(input("Enter the first angle of a triangle: "))
y = int(input("Enter the second angle of a triangle: "))
z = int(input("Enter the third angle of a triangle: "))
if x+y+z == 180 :
  print("the given angles forms a triangle")
else:
  print("this doesnt form a triangle")

Enter the first angle of a triangle: 100
Enter the second angle of a triangle: 100
Enter the third angle of a triangle: 100
this doesnt form a triangle

### `Problem 3`: Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit.

In [ ]:
cp = int(input("Enter the cost price: "))
sp = int(input("Enter the selling price: "))
if cp > sp :
  print("You incured a loss")
elif sp > cp :
  print("you got a profit of : ",sp-cp)
else:
  print("you neither got loss or profit")

Enter the cost price: 100
Enter the selling price: 100
you neither got loss or profit

### `Problem 4`: Write a menu-driven program -
1. cm to ft
2. km to miles
3. USD to INR
4. exit

In [4]:
menu = int(input (
    '''Enter the required option
    1. Press 1 to convert cm to ft
    2. press 2 to convert km to miles
    3. Press 3 to convert usd to inr
    4. Press 4 to exit'''
))
if menu == 1:
  cm = int(input("Enter the distance in cm"))
  ft = cm*0.03280
  print("Distance in feet is: ",ft , " Feet")
elif menu == 2:
  km = int(input("Enter the distance in km"))
  mile = km*0.621371
  print("Distance in miles is: ",mile , " miles")
elif menu == 3:
  usd = int(input("Enter the value in usd"))
  inr = usd*82.3
  print("value in inr is: ",inr , " rupee")
else:
  print("Exit program")

Enter the required option
    1. Press 1 to convert cm to ft
    2. press 2 to convert km to miles
    3. Press 3 to convert usd to inr
    4. Press 4 to exit4
Exit program

### `Problem 5` - Exercise 12: Display Fibonacci series up to 10 terms.

*Note: The Fibonacci Sequence is a series of numbers. The next number is found by adding up the two numbers before it. The first two numbers are 0 and 1. For example, 0, 1, 1, 2, 3, 5, 8, 13, 21. The next number in this series above is 13+21 = 34*

In [6]:
num1, num2 = 0, 1
for i in range (0,10):
  print (num1)
  next = num1 + num2
  num1 = num2
  num2 = next

0
1
1
2
3
5
8
13
21
34

### `Problem 6` - Find the factorial of a given number.

Write a program to use the loop to find the factorial of a given number.

The factorial (symbol: `!`) means to multiply all whole numbers from the chosen number down to 1.

For example: calculate the factorial of 5

```bash
5! = 5 × 4 × 3 × 2 × 1 = 120
```

Output:

```bash
120
```

In [17]:
num1 = int(input("enter a number"))
fact = 1
for i in range(1,num1+1):
  fact = fact*i
print(fact)

enter a number5
120

### `Problem 7` - Reverse a given integer number.

Example:

`Input:`

```bash
76542
```

`Output:`

```bash
24567
```

In [18]:
num1 = int(input("enter the integer"))
rev = 0
while(num1 != 0):
  last = num1%10
  rev = rev*10+ last
  num1 = num1// 10

print("revrse is: ", rev)

enter the integer1234
revrse is:  4321

### `Problem 8`: Take a user input as integer N. Find out the sum from 1 to N. If any number if divisible by 5, then skip that number. And if the sum is greater than 300, don't need to calculate the sum further more. Print the final result. And don't use for loop to solve this problem.

**Example 1:**

`Input:`

```bash
30
```

`Output:`

```bash
276
```

In [5]:
sum = 0
n = int(input("enter the value of n "))
i = 1
while i < n+1 :
  if i%5 == 0:
    i+= 1
    continue
  sum+= i
  if sum > 300:
    sum = sum-i
    break
  i+= 1
print(sum)

enter the value of n 50
276

### `Problem 9`: Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers.

In [8]:
count= 0
sum = 0
while True:
  n = int(input("enter the value of n "))
  count+= 1
  if(n==0):
    break
  else:
    sum = sum+n
    average = sum/count

print(sum, average)

enter the value of n 1
enter the value of n 2
enter the value of n 3
enter the value of n 4
enter the value of n 5
enter the value of n 0
15 3.0

###`Problem 9`: Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.

In [11]:
list = []
for i in range(2000,3201):
  if i % 7 == 0 and i % 5 != 0 :
    list.append(str(i))
print(",".join(list))

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199

###`Problem 10`: Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. The numbers obtained should be printed in a space-separated sequence on a single line.

In [16]:

list = []
for i in range(1000,3001):
  flag = True
  curr = i
  while curr > 0:
    last = curr%10
    if last % 2 != 0:
      flag = False
      break
    curr = curr//10
  if flag:
    list.append(str(i))
print(",".join(list))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888

###`Problem 11`: A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps.
The trace of robot movement is shown as the following:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
> The numbers after the direction are steps.

> `!` means robot stop there.

**Please write a program to compute the distance from current position after a sequence of movement and original point.**

*If the distance is a float, then just print the nearest integer.*

Example:

`Input`:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
`Output`:
```
2
```

In [17]:
pos = [0,0]
while True:
  s = input("enter the robot path")
  if s == '!':
    break
  direction = s.split()[0]
  steps = int(s.split()[1])
  if direction == 'UP':
    pos[1] = pos[1]+steps
  elif direction == 'DOWN':
    pos[1] = pos[1]-steps
  elif direction == 'LEFT':
    pos[0] = pos[0]-steps
  elif direction == 'RIGHT':
    pos[0] = pos[0]+steps
  else:
    pass
print((pos[0]**2+pos[1]**2)**0.5)

enter the robot pathUP 5
enter the robot pathDOWN 5
enter the robot pathRIGHT 5
enter the robot pathLEFT 5
enter the robot path!
0.0

###`Problem 12`:Write a program to print whether a given number is a prime number or not

In [20]:
n = int(input("Enter a number: "))
flag = True
for i in range(2,n):
  if n% i == 0:
    flag = False
    break
if(flag):
  print('prime')
else:
  print('not a prime')

Enter a number: 18
not a prime

###`Problem 13`:Print all the Armstrong numbers in a given range.
Range will be provided by the user<br>
Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are the Armstrong numbers.

In [ ]:
start = int(input("Enter the start of the range: "))
end = int(input("Enter the end of the range: "))

for num in range(start, end+1):
    temp = num
    sum = 0
    order = len(str(num))
    while temp > 0:
        digit = temp % 10
        sum += digit ** order
        temp //= 10
    if num == sum:
        print(num)

###`Problem 14`:Calculate the angle between the hour hand and minute hand.

Note: There can be two angles between hands; we need to print a minimum of two. Also, we need to print the floor of the final result angle. For example, if the final angle is 10.61, we need to print 10.

Input:<br>
H = 9 , M = 0<br>
Output:<br>
90<br>
Explanation:<br>
The minimum angle between hour and minute
hand when the time is 9 is 90 degress.

In [ ]:
h = int(input('Enter hours hand-'))
m = int(input('Enter minute hand-'))

# validate the input
if (h < 0 or m < 0 or h > 12 or m > 60):
    print('Wrong input')

# Idea is to minute angle - hour agnle from clockwise from 12 hour point

# 1 minute in minute angle manke 6 degree. (60 minute -> 360 degree)
m_angle = m*6

# every hour point yeilds to 30degree-- 12 hours-360degree plus if minute hand moves hour hands move too
# Every minute after hour hand take 0.5 degree movement. clockwise
h_angle = h*30 + m*0.5

# Take abs difference b/w them
angle = abs(h_angle - m_angle)


if angle>180:
    print(360-angle)
else:
    print(angle)

###`Problem 15`:Given two rectangles, find if the given two rectangles overlap or not. A rectangle is denoted by providing the x and y coordinates of two points: the left top corner and the right bottom corner of the rectangle. Two rectangles sharing a side are considered overlapping. (L1 and R1 are the extreme points of the first rectangle and L2 and R2 are the extreme points of the second rectangle).

Note: It may be assumed that the rectangles are parallel to the coordinate axis.

<img src='https://www.geeksforgeeks.org/wp-content/uploads/rectanglesOverlap.png' width='300' height='200'>

In [ ]:
print("Enter both Rectangel points coordinates <x y>")

l1_x, l1_y = list(map(int, input('Enter L1 coordinate value  (Two value space seperated):').split()))
r1_x, r1_y = list(map(int, input('Enter r1 coordinate value,(Two value space seperated):').split()))

l2_x, l2_y = list(map(int, input('Enter L2 coordinate value,(Two value space seperated):').split()))
r2_x, r2_y = list(map(int, input('Enter r2 coordinate value,(Two value space seperated):').split()))

# if rectangle has area 0, no overlap
if l1_x == r1_x or l1_y == r1_y or r2_x == l2_x or l2_y == r2_y:
  print("Don't Overlap")

# If one rectangle is on left side of other
elif l1_x > r2_x or l2_x > r1_x:
  print("Don't Overlap")

# If one rectangle is above other
elif r1_y > l2_y or r2_y > l1_y:
  print("Don't Overlap")
else:
  print("Overlap")